makkyo1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mk.urls')),
    path('task/', include('task.urls')),
    path('bmi/', include('bmi.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mk/urls.py
from django.urls import path
from . import views

app_name = 'mk'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('registration/', views.Registration.as_view(), name='registration'),  
    path('registration/complete', views.RegistrationComp.as_view(), name='registration_complete'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('profile/<int:pk>/update/', views.ProfileUpdate.as_view(), name='profile_update'),
    path('profile/<int:pk>/password', views.PasswordChange.as_view(), name='password'),
    path('profile/<int:pk>/password/complete', views.PasswordChangeComplete.as_view(), name='password_complete'),
]

task/urls.py
from django.urls import path
from . import views

app_name = 'task'

urlpatterns = [
    path('', views.taskTop.as_view(), name='task_top'),
    path('build_project/', views.BuildProject.as_view(), name='build_project'),
    path('ProjectPage/<int:pk>/', views.ProjectPage.as_view(), name='our_project'),
    path('ProjectPage/<int:pk>/detail', views.ProjectDetail.as_view(), name='our_project_detail'),
    path('ProjectPage/<int:pk>/update', views.ProjectUpdate.as_view(), name='our_project_update'),
    path('ProjectPage/<int:pk>/delete', views.ProjectDelete.as_view(), name='our_project_delete'),
    path('ProjectPage/<int:pk>/projecttousers_form', views.UpdateProjectMember.as_view(), name='projecttousers_form'),
    path('ProjectPage/<int:pk>/delete_member', views.ProjectDeleteMember.as_view(), name='our_project_delete_member'),
    path('ProjectPage/<int:pk>/AATask', views.AddTaskForAjax.ajax_response, name='add_task'),
    path('ajax/getProjectTaskInfo',views.getProjectTaskInfoAjax.ajax_response, name='getPJTask')
]

task/models.py
from django.db import models
from mk.models import User

"プロジェクトモデル"
class Project(models.Model):
    project_cd = models.AutoField(
        primary_key=True
    )

    name = models.CharField(
        max_length=25,
        verbose_name='プロジェクト名'
    )

    leader = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='leader',
        verbose_name='プロジェクトリーダー'
    )

    start_date = models.DateField(
        null=True,
        blank=True,
        verbose_name='開始日'
    )

    end_date = models.DateField(
        null=True,
        blank=True,
        verbose_name='終了日'
    )

    details = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name='詳細'
    )

    update_date = models.DateField(
        auto_now=True
    )
 
    is_delete = models.BooleanField(
        default=False
    )

"プロジェクトメンバーモデル"
class ProjectMember(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    member = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.project} - {self.member}'

"プロジェクト To ユーザ (1 対 多) "
class ProjectToUsers(models.Model):
    project_cd = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )

    user_cd = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

class Task(models.Model):
    PRIOLITY_NUMBER = (
        (0, '未選択'),
        (1, '最低'),
        (2, '低'),
        (3, '常'),
        (4, '高'),
        (5, '最高')
    )
    task_cd = models.AutoField(
        primary_key=True,
        default=1,
    )
    

    task_name = models.CharField(
        max_length=100,
        verbose_name='タスク名'
    )

    user_name = models.CharField(
        max_length=30,
        null=True,
        blank=True,
        verbose_name='担当者名'
    )

    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='担当者'
    )

    start_date = models.DateField(
        null=True,
        blank=True,
        verbose_name='開始日'
    )

    end_date = models.DateField(
        null=True,
        blank=True,
        verbose_name='終了日'
    )

    details = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name='詳細'
    )

    priolity = models.IntegerField(
        choices=PRIOLITY_NUMBER,
        default=0
    )

    update_date = models.DateField(
        auto_now=True
    )

    is_delete = models.BooleanField(
        default=False
    )
   
    def __str__(self):
        return self.task_name

"プロジェクト To タスク (1 対 多) "
class ProjectToTask(models.Model):
    project_cd = models.ForeignKey(
        Project,
        on_delete=models.CASCADE
    )

    task_cd = models.ForeignKey(
        Task,
        on_delete=models.CASCADE
    )

task/forms.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django import forms
from .models import Project, ProjectToUsers

User = get_user_model()

"プロジェクト作成"
class ProjectCreate(forms.ModelForm):

    class Meta:
        model = Project
        fields = (
            'name', 'leader',
            'start_date', 'end_date',
            'details'
       )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['leader'].widget.attrs['hidden'] = 'true'
        self.fields['start_date'].widget.input_type = "date"
        self.fields['end_date'].widget.input_type="date"

"プロジェクト更新"
class ProjectUpdateForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = (
            'name',
            'start_date', 'end_date',
            'details'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['start_date'].widget.input_type = "date"
        self.fields['end_date'].widget.input_type="date"

"プロジェクト削除"
class ProjectDeleteForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = (
            'is_delete',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['is_delete'].widget.attrs['hidden'] = 'true'

"メンバー追加"
class AddProjectMember(forms.ModelForm):

    class Meta:
        model = ProjectToUsers
        fields = (
            'project_cd',
            'user_cd'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        where = []

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['project_cd'].widget.attrs['hidden'] = 'true'

        leader = Project.objects.filter(project_cd=self.initial["project_cd"])
        in_member = ProjectToUsers.objects.filter(project_cd=self.initial["project_cd"])
        staff = User.objects.filter(is_staff=1)
        non_active = User.objects.filter(is_active=0)

        where.append(leader[0].leader_id)
        for in_men in in_member:
            where.append(in_men.user_cd_id)

        for s in staff:
            where.append(s.pk)

        for non in non_active:
            where.append(non.pk)

        result = User.objects.exclude(pk__in=where)

        self.fields['user_cd'].queryset = result

task/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import redirect, resolve_url, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db import models
from .models import ProjectToUsers, Project
from .forms import ProjectCreate, ProjectUpdateForm, ProjectDeleteForm, AddProjectMember

from django.views.generic.edit import DeleteView

from django.urls import reverse_lazy

from django.http.response import JsonResponse
from django.core import serializers
from .models import ProjectToUsers, Project, ProjectToTask, Task

from django.views.decorators.csrf import csrf_exempt

User = get_user_model()

"トップページ"
class taskTop(LoginRequiredMixin, generic.TemplateView):
    template_name = 'task/task_top.html'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)

        project_user = ProjectToUsers.objects.filter(user_cd=user.pk)
        leader = Project.objects.filter(leader=user.pk, is_delete=0)

        if len(project_user) > 0:
            context['member'] = []
            for person in project_user:
                member = Project.objects.filter(project_cd=person.project_cd.pk, is_delete=0)
                context['member'].extend(member)
        else:
            context['member'] = None
  
        context['leader'] = leader if len(leader) > 0 else None

        return context

"プロジェクト作成"
class BuildProject(LoginRequiredMixin, generic.CreateView):
    model = Project
    form_class = ProjectCreate
    success_url = '/task/'
    template_name = 'task/build_project.html'

    def get_initial(self):
        leader = self.request.user.pk
        return {'leader': leader,}

"プロジェクト限定"
class ProjectUserOnlyMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        is_return = True

        user = self.request.user

        l_result = Project.objects.filter(leader=user.id, project_cd=self.kwargs["pk"])
        m_result = ProjectToUsers.objects.filter(project_cd=self.kwargs["pk"], user_cd=self.request.user.pk)
        p_result = Project.objects.filter(project_cd=self.kwargs["pk"], is_delete=0)

        if len(l_result) == 0 and len(m_result) == 0:
            is_return = False

        if len(p_result) == 0:
            is_return = False

        return is_return

"プロジェクトページ"
class ProjectPage(ProjectUserOnlyMixin, generic.TemplateView):
    template_name = 'task/our_project.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)

        project = Project.objects.filter(project_cd=self.kwargs["pk"])
        p_user = ProjectToUsers.objects.filter(project_cd=self.kwargs["pk"])

        if len(p_user) > 0:
            context['member'] = []
            for person in p_user:
                member = User.objects.filter(pk=person.user_cd.pk)
                context['member'].extend(member)
        else:
            context['member'] = None

        context['project'] = project if len(project) > 0 else None
        context['task'] = None

        return context

"プロジェクトリーダー限定"
class ProjectLeaderOnlyMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        is_return = True

        user = self.request.user

        l_result = Project.objects.filter(leader=user.id, project_cd=self.kwargs["pk"])
        p_result = Project.objects.filter(project_cd=self.kwargs["pk"], is_delete=0)

        if len(l_result) == 0:
            is_return = False

        if len(p_result) == 0:
            is_return = False

        return is_return

"プロジェクト情報"
class ProjectDetail(ProjectUserOnlyMixin, generic.DetailView):
    model = Project
    templates_name = 'task/project_detail.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)

        p_user = ProjectToUsers.objects.filter(project_cd=self.kwargs["pk"])
        project = Project.objects.filter(project_cd=self.kwargs["pk"], is_delete=0)

        context['member'] = p_user if len(p_user) > 0 else None

        context['project'] = project if len(project) > 0 else None

        return context

"プロジェクト更新ページ"
class ProjectUpdate(ProjectUserOnlyMixin, generic.UpdateView):
    model = Project
    template_name = 'task/project_update.html'
    form_class = ProjectUpdateForm

    def get_success_url(self):
        return resolve_url('task:our_project_detail', pk=self.kwargs["pk"])

"プロジェクト削除ページ"
class ProjectDelete(ProjectLeaderOnlyMixin, generic.UpdateView):
    model = Project
    template_name = 'task/project_delete.html'
    form_class = ProjectDeleteForm

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)

        p_user = ProjectToUsers.objects.filter(project_cd=self.kwargs["pk"])
        project = Project.objects.filter(project_cd=self.kwargs["pk"], is_delete=0)

        if len(p_user) > 0:
            context['member'] =[]
            for person in p_user:
                member = User.objects.filter(pk=person.user_cd.pk)
                context['member'].extend(member)
        else:
            context['member'] = None

        context['project'] = project if len(project) > 0 else None

        return context

    def get_initial(self):
        return {'is_delete': True,}

    def get_success_url(self):
        return resolve_url('task:task_top')

"プロジェクトメンバー追加"


"プロジェクトメンバー更新"
class UpdateProjectMember(ProjectUserOnlyMixin, generic.CreateView):
    model = ProjectToUsers
    templates_name = "task/projecttousers_form.html"
    form_class = AddProjectMember

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)

        p_user = ProjectToUsers.objects.filter(project_cd=self.kwargs["pk"])
        project = Project.objects.filter(project_cd=self.kwargs["pk"], is_delete=0)

        context['member'] = p_user if len(p_user) > 0 else None

        context['project'] = project if len(project) > 0 else None

        return context

    def get_success_url(self):
        return resolve_url('task:projecttousers_form', pk=self.kwargs["pk"])

    def get_initial(self):
        pc = self.kwargs["pk"]
        return {'project_cd': pc,}

"プロジェクトメンバー削除"
class ProjectDeleteMember(ProjectLeaderOnlyMixin, generic.DeleteView):
    model = ProjectToUsers
    success_url = reverse_lazy('task:projecttousers_form')

    def post(self, request, *args, **kwargs):
        delete_ids = request.POST.getlist('delete_ids')
        if delete_ids:
            ProjectToUsers.objects.filter(id__in=delete_ids).delete()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):

        return super().form_valid(form)

"タスク追加"
class AddTaskForAjax():

    def ajax_response(self, *args, **kwargs):
        taskName = self.POST['taskName']

        if self.POST['user'] != "":
            user = User.objects.get(pk=self.POST['user'])
        else:
            user = None

        if user == None:
            userName = self.POST['userName'] if self.POST['userName'] != "" else None
        else:
            userName =  None

        details = self.POST['details'] if self.POST['details'] != "" else None
        startDate = self.POST['startDate'] if self.POST['startDate'] != "" else None
        endDate = self.POST['endDate'] if self.POST['endDate'] != "" else None
        priolity = self.POST['priolity'] if self.POST['priolity'] != "" else None

        task = Task.objects.create(
            task_name=taskName, user=user,
            user_name=userName, details=details,
            start_date=startDate, end_date=endDate,
            priolity=priolity
        )

        projectCd = kwargs['pk']

        project = Project.objects.get(project_cd=projectCd)

        result = ProjectToTask.objects.create(
            project_cd=project, task_cd=task
        )

        projectTask = ManupilateDataBase.getProjectTask(projectCd)
 
        json_serializer = serializers.get_serializer("json")()
        taskData = json_serializer.serialize(projectTask, ensure_ascii=False)

        return JsonResponse({"taskdata" : taskData})
  

" DB操作クラス "
class ManupilateDataBase():
    
    def getJoinProject(joinCd):
        p_user = ProjectToUsers.objects.filter(user_cd=joinCd)

        if len(p_user) > 0:
            result = []
            for p in p_user:
                member = Project.objects.filter(project_cd=p.project_cd.pk, is_delete=0)
                result.extend(member)

        else:
            result = None

        return result

    def getProjectTask(projectCd):
        p_task = ProjectToTask.objects.filter(project_cd=projectCd)

        if len(p_task) > 0:
                task = Task.objects.filter(projecttotask__project_cd=projectCd)
                return task if task.exists() else None

    def getProjectMember(memberCd):
        p_user =  ProjectToUsers.objects.filter(project_cd=memberCd)

        if len(p_user) > 0:
            result = []
            for person in p_user:
                member = User.objects.filter(pk=person.user_cd.pk)
                result.extend(member)
        else:
            result = None

        return result

    def getTaskInfo(taskCd):
        task = Task.objects.filter(task_cd=taskCd)

        if len(task) > 0:
            return task
        else:
            return None

    def getUserInfo(userCd):
        user = User.objects.filter(use_cd=userCd)

        if len(user) > 0:
            return user
        else:
            return None

"プロジェクトタスク情報取得"
class getProjectTaskInfoAjax():

    @csrf_exempt

task/templates/task/build_project.html
{% extends "base.html" %}
{% block title %} Makkyo {% endblock %}
{% block mainT %} プロジェクト作成 {% endblock %}
{% block body %}

<div style="padding:20px 200px 0px 200px;">
    <div class="createArea">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn btn-primary">登録</button>
            <a href="{% url 'task:task_top' %}" class="btn btn-secondary">戻る</a>
        </form>
    </div>
</div>
{% endblock %}

task/templates/task/delete_member.html
{% extends "base.html" %}
{% block title %} メンバー削除の確認 {% endblock %}
{% block mainT %} メンバー削除の確認 {% endblock %}
{% block body %}
<div class="container">
  <h1>削除の確認</h1>
  <p>選択されたメンバーを削除しますか?</p>
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="delete_ids" value="{{ object.id }}">
    <button type="submit" class="btn btn-danger">削除する</button>
    <a href="{% url 'task:update_member' pk=object.project_id %}" class="btn btn-primary">キャンセル</a>
  </form>
</div>
{% endblock %}

task/templates/task/our_project.html
{% extends "base.html" %}
{% block title %} Makkyo {% endblock %}
{% block mainT %} {{ project.0.name }} {% endblock %}
{% block body %}

<nav class=" navbar-dark bg-dark flex-md-nowrap p-0 header">
    <a class="navbar-brand col-md-1 mr-0" href="/task/">戻る</a>
    <a class="navbar-brand col-md-2 mr-0" href="{% url 'task:our_project_detail' project.0.pk %}"> プロジェクト詳細</a>
    <a class="navbar-brand col-md-2 mr-0" href="#" id="CTB">タスク追加</a>
    <div class="btn-group">
        <div class="btn dropdown-toggle naviDrop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            メンバー
        </div>
            <div class="dropdown-menu dropdown-menu-right" >
                <a class="dropdown-item" href="#"> {{ project.0.leader }} </a>
                {% if member != None %}
                    <div class="dropdown-divider"></div>
                    {% for person in member %}
                    <a class="dropdown-item" href="#"> {{ person }} </a>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</nav>

<div id="taskList">
    {% if task == None %}
        <ul>
            <li>タスクがありません</li>
        </ul>
    {% else %}
        <ul id="taskAccordion">
            {% for content in task %}
        
                <li class="selectTask task{{content.priolity}}" value="{{content.task_cd}}">{{content.task_name}}</li>
            {% endfor %}
        </ul>
    {% endif %}

</div>

<div id="modal-task-add">
    <h4>追加タスク</h4>
    <form name="addTask" method="POST" action="{% url 'task:add_task' project.0.pk %}">
        <table class="table">
            <tr>
                <th>タスク名</th>
                <td><input type="text" name="taskName" style="width:80%;"></td>
            </tr>
            <tr>
                <th>担当</th>
                <td>
                    <select name="user" id="selectC" style="width:80%;">
                        <option value="">---</option>
                        <option value={{ project.0.leader.pk }}>{{ project.0.leader }}</option>
                        {% for person in member %}
                            <option value={{ person.pk }}>{{ person }}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <th></th>
                <td><input type="text" id="writeCN" name="userName" style="width:80%;"></td>
            </tr>
            <tr>
                <th>詳細</th>
                <td><textarea name="details" rows="4" cols="50" style="width:80%;"></textarea></td>
            </tr>
            <tr>
                <th>開始日</th>
                <td> 
                    <input type="date" name="startDate" style="width: 80%;">
                </td>
            </tr>
            <tr>
                <th>終了日</th>
                <td>
                    <input type="date" name="endDate" style="width: 80%;">
                </td>
            </tr>
            <tr>
                <th>優先度</th>
                <td>
                    <input type="range" name="priolity" min="1" max="5" value="3" style="width: 80%;"> &emsp; <span id="priolityNo" style="font-size:14px;">3</span>
                    <br>
                    <p>数値が大きいほど優先度<font color="red">大</font>!</p>
                </td>
            </tr>
        </table>
        {% csrf_token %}
    </form>
    <button type="button" id="CTBC" class="btn btn-primary" style="margin-right:10px;">キャンセル</button>
    <button type="button" id="TaskAddAjax" class="btn btn-success" id="addTask">追加</button>
</div>

<div id="modal-task-details"></div>
<button type="button" id="TDI" style="display:none;"></button>

{% endblock %}

task/templates/task/project_detail.html
{% extends "base.html" %}
{% block title %} Makkyo {% endblock %}
{% block mainT %} {{ project.0.name }} 詳細情報 {% endblock %}
{% block body %}
<div style="margin:20px">
    <table class="table">
        <tbody>
            <tr> 
                <th>プロジェクト名</th>
                <td>{{ project.0.name }}</td>
            </tr>
            <tr> 
                <th>開始日</th>
                <td>{{ project.0.start_date }}</td>
            </tr>
            <tr>
                <th>終了日</th>
                <td>{{ project.0.end_date }}</td>
            </tr>
            <tr>
                <th>詳細</th>
                <td>{{ project.0.details }}</td>
            </tr>
            <tr>
                <th>リーダー</th>
                <td>{{ project.0.leader }}</td>
            </tr>
            <tr>
                <th>メンバー</th>
                <td>
                    {% if member != None %}
                        <table class="no_border">
                            {% for person in member %}
                                <tr>
                                    <td>
                                        {{ person.user_cd }}
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    {% else %}
                        メンバーはいません
                    {% endif %}
                </td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-outline-secondary" href="{% url 'task:projecttousers_form' project.0.pk %}">メンバー更新</a>
    <hr>
    <a href="{% url 'task:our_project' project.0.pk %}" class="btn btn-primary" styloe="width: 120px; margin-right:10px;">戻る</a>
    <a href="{% url 'task:our_project_update' project.0.pk %}" class="btn btn-primary ">変更</a>
    {% if user == project.0.leader %}
        <a href="{% url 'task:our_project_delete' project.0.pk %}" class="delete-btn btn btn-primary">削除</a>
    {% endif %}
</div>
{% endblock %}
                                        

task/templates/task/projecttousers_form.html
{% extends "base.html" %}
{% block title %} Makkyo {% endblock %}
{% block mainT %} メンバー更新 {% endblock %}
{% block body %}

<div style="margin:30px 80px;">
    <form method="post" action="{% url 'task:our_project_delete_member' project.0.pk%}" >
        <table class="table">
            <tbody>
                <tr>
                    <th>リーダー</th>
                    <td>{{ project.0.leader }}</td>
                </tr>
                <tr>
                    <th>メンバー</th>
                    <td>
                        {% if member != None %}
                            <table class="no_border">
                                <thead class="MDC">
                                    <tr>
                                        <th>ユーザー名</th>
                                        <th>選択</th>
                                    </tr>
                                </thead>
                                {% for person in member %}
                                    <tr>
                                        <td>
                                            {{ person.user_cd }}
                                        </td>
                                        <td class="MDC">
                                            <input type="checkbox" class="CCB" name="delete_ids" value="{{ person.id }}">
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        {% else %}
                            メンバーはいません
                        {% endif %}
                    </td>
                </tr>
            </tbody>
        </table>
        <a href="{% url 'task:our_project_detail' project.0.pk %}" class="btn btn-primary MD">戻る</a>
        <a class="btn btn-primary MD" style="color: white;" id="AMB">メンバー追加</a>
        {% if member != None and user == project.0.leader %}
            <a class="btn btn-primary MD MDB" style="color:white; margin-left: 10px;">メンバー離脱</a>
            <a class="btn btn-primary MDC MDCB" style="color:white; margin-left: 10px;">キャンセル</a>
            <input class="delete-btn btn btn-primary MDC CPB" style="margin-left: 10px;" type="submit" value="離脱">
            {% csrf_token %}
        {% endif %}
    </form>
</div>

<div id="modal-member">
    <form action="" method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="form-group">
            {% if field.label != "Project cd" %}
                <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {% endif %}
            {{ field }}
            <span style="color:red">{{ field.errors }}<span>
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-success btn-lg">追加</button>
        <a class="btn btn-primary btn-lg" style="color: white;" id="AMCB">戻る</a>
    </form>
</div>
{% endblock %}

task/templates/task/task_top.html
{% extends "base.html" %}
{% block title %} Makkyo {% endblock %}
{% block mainT %} タスク {% endblock %}
{% block body %}

    <div class="leftArea">
        <h2 class="eleTitle">主導プロジェクト</h2>
        {% if leader != None %}
            {% for lead in leader %}
                <a class="project_area" href="{% url 'task:our_project' lead.pk %}">
                    <div>
                        <h4>{{lead.name}}</h4>
                        <p>リーダー: {{lead.leader}}</p>
                        {% if lead.start_date != None %}
                            <p>開始日: {{lead.start_date}}</p>
                        {% endif %}
                        {% if lead.end_date != None %}
                            <p>終了日: {{lead.end_date}}</p>
                        {% endif %}
                        {% if lead.details != None %}
                            <p>詳細: {{lead.details}}</p>
                        {% endif %}
                    </div>
                </a>
            {% endfor %}
        {% else %}
            <h4>プロジェクトがありません</h4>
        {% endif %}
        <a class="btn btn-outline-secondary" href="/task/build_project/">プロジェクト作成</a>
    </div>
    <div class="rightArea">
        <h2 class="eleTitle">参加プロジェクト</h2>
        {% if member != None %}
            {% for men in member %}
                <a class="project_area" href="{% url 'task:our_project' men.pk %}">
                    <div>
                        <h4>{{men.name}}</h4>
                        <p>リーダー: {{men.leader}}</p>
                        {% if men.start_date != None %}
                            <p>開始日: {{men.start_date}}</p>
                        {% endif %}
                        {% if men.end_date != None %}
                            <p>終了日: {{men.end_date}}</p>
                        {% endif %}
                        {% if men.details != None %}
                            <p>詳細: {{men.details}}</p>
                        {% endif %}
                    </div>
                </a>
            {% endfor %}
        {% else %}
            <h4>プロジェクトがありません</h4>
        {% endif %}
    </div>
{% endblock %}