makkyo1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mk.urls')),
    path('task/', include('task.urls')),
    path('bmi/', include('bmi.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mk/urls.py
from django.urls import path
from . import views

app_name = 'mk'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('registration/', views.Registration.as_view(), name='registration'),  
    path('registration/complete', views.RegistrationComp.as_view(), name='registration_complete'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('profile/<int:pk>/update/', views.ProfileUpdate.as_view(), name='profile_update'),
    path('profile/<int:pk>/password', views.PasswordChange.as_view(), name='password'),
    path('profile/<int:pk>/password/complete', views.PasswordChangeComplete.as_view(), name='password_complete'),
]

mk/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django import forms

class User(AbstractUser, models.Model):
    gender = models.CharField(verbose_name='性別', max_length=3, choices=[('男性','男性'),('女性','女性'),('その他','その他')], blank=True, null=True)
    birthdate = models.DateField(verbose_name='生年月日', blank=True, null=True)
    icon = models.ImageField(
        upload_to='img/',
        verbose_name='アイコン',
        blank=True,
    )

# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey('MkUser', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class MkUser(models.Model):
    id = models.BigAutoField(primary_key=True)
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()
    gender = models.CharField(max_length=10)
    birthdate = models.DateField(max_length=10)

    class Meta:
        managed = False
        db_table = 'mk_user'


class MkUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(MkUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'mk_user_groups'
        unique_together = (('user', 'group'),)


class MkUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(MkUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'mk_user_user_permissions'
        unique_together = (('user', 'permission'),)

        

mk/forms.py
from django import forms
from django.contrib.auth.forms import( AuthenticationForm )
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()

"アカウント登録フォーム"
class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'username', 'email',
            'password1', 'password2',
        )
   
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

"アカウント更新フォーム"
class AccountsUpdateForm(forms.ModelForm):
    GENDER_CHOICES = [ 
        ('男性', '男性'),
        ('女性', '女性'),
        ('その他', 'その他'),
    ]
    gender = forms.ChoiceField(label='性別', choices=GENDER_CHOICES)
    birthdate = forms.DateField(label='生年月日', widget=forms.DateInput(attrs={'type': 'date'}),)

    class Meta:
        model = User
        fields = (
            'icon',
            'username', 'email',
            'birthdate', 'gender',
            'last_name', 'first_name',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

"ログインフォーム"
class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

mk/views.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect, resolve_url, render
from .forms import LoginForm, RegistrationForm, AccountsUpdateForm

from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import get_user_model
from .forms import RegistrationForm

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import ( LoginView, LogoutView )

from django.views import generic
from django.contrib.auth.decorators import login_required
from .forms import LoginForm

" ログイン要求"
def profile(request):
    if request.method == 'POST':
        form = AccountsUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('mk:profile')
    else:
        form = AccountsUpdateForm(instance=request.user)

    context = {
        'user': user,
        'form': form,
    }

    return render(request, 'profile.html', context)

User = get_user_model()

"ユーザー限定クラス"
class UserOnlyMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser

"ユーザー情報表示ページ"
class Profile(UserOnlyMixin, generic.DetailView):
    model = User
    template_name = 'profile.html'

"ユーザー情報更新ページ"
class ProfileUpdate(UserOnlyMixin, generic.UpdateView):
    model = User
    form_class = AccountsUpdateForm
    template_name = 'profile_update.html'

    def get_success_url(self):
        return resolve_url('mk:profile', pk=self.kwargs['pk'])

"アカウント登録ページ"
class Registration(generic.CreateView):
    model = User
    template_name = 'registration.html'
    form_class = RegistrationForm
    success_url = 'registration/complete'

"アカウント登録完了"
class RegistrationComp(generic.TemplateView):
    template_name = 'registration_complete.html'

"ログインページ"
class Login(LoginView):
    template_name = 'login.html'
    form_class = LoginForm

"トップページ"
class Top(LoginRequiredMixin, generic.TemplateView):
    template_name = 'top.html'
    redirect_field_name = 'redirect_to'

"ログアウトページ"
class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'logout.html'

"パスワード変更ページ"
class PasswordChange(UserOnlyMixin, PasswordChangeView):
    model = User
    template_name = 'password_change.html'

    def get_success_url(self):
        return resolve_url('mk:password_complete', pk=self.kwargs['pk'])

"パスワード変更完了"
class PasswordChangeComplete(UserOnlyMixin, PasswordChangeDoneView):
    template_name = 'password_change_complete.html'

mk/templates/base.html
<!DOCTYPE html>
<html lang='ja'>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/export.png' %}">

        <title>{% block title %}{% endblock %}</title>

        <link href="{% static 'bootstrap/dist/css/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap/dist/css/bootstrap-grid.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap/dist/css/bootstrap-grid.min.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap/dist/css/bootstrap-reboot.css' %}" rel="styleheet">
        <link href="{% static 'bootstrap/dist/css/bootstrap-reboot.min.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap/docs/4.0/examples/dashboard/dashboard.css' %}" rel="stylesheet">

        <link href="{% static 'css/adjustment.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/navibar.css' %}" rel="stylesheet" type="text/css">

        <link href="{% static 'css/modal.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'css/slider.css' %}" rel="stylesheet" type="text/css">
       
        <link href="{% static 'css/bmi.css' %}" rel="stylesheet" type="text/css">
        

        <script type="text/javascript" src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
  
        <script src="{% static 'bootstrap/assets/js/vendor/anchor.min.js' %}"></script>
        <script src="{% static 'bootstrap/assets/js/vendor/clipboard.min.js' %}"></script>
        <script src="{% static 'bootstrap/assets/js/vendor/holder.min.js' %}"></script>
        <script src="{% static 'bootstrap/assets/js/vendor/popper.min.js' %}"></script>
        <script src="{% static 'bootstrap/dist/js/bootstrap.bundle.js' %}"></script>
        <script src="{% static 'bootstrap/dist/js/bootstrap.bungle.min.js' %}"></script>
        <script src="{% static 'bootstrap/dist/js/bootstrap.js' %}"></script>
        <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/dist/alert.js' %}"></script>
        <script src="{% static 'bootstrap/js/dist/button.js' %}"></script>
        <script src="{% static 'bootstrap/js/dist/carousel.js' %}"></script>
        <script src="{% static 'bootstrap/js/dist/collapse.js' %}"></script>
        <script src="{% static 'bootstrap/js/dist/dropdown.js' %}"></script>
        <script src="{% static 'bootstrap/js/dist/index.js' %}"></script>
        <script src="{% static 'bootstrap/js/dist/modal.js' %}"></script>
        <script src="{% static 'bootstrap/js/dist/scrollspy.js' %}"></script>
        <script src="{% static 'bootstrap/js/dist/tab.js' %}"></script>
        <script src="{% static 'bootstrap/js/dist/tooltip.js' %}"></script>
        <script src="{% static 'bootstrap/js/dist/util.js' %}"></script>

        <script src="{% static 'js/navibar.js' %}"></script>
        <script src="{% static 'js/modal.js' %}"></script>
        <script src="{% static 'js/masta.js' %}"></script>
        <script src="{% static 'js/ajax.js' %}"></script>
        <script src="{% static 'js/clock.js' %}"></script>
    </head>

    <body>
        <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
            <a class="navbar-brand col-sm-3 col-md-2 mr-0 barbtn" href="">Makkyo</a>
            <div class="form-control form-control-dark w-100">{% block mainT %}{% endblock %}</div>
            <div class="btn-group">
                <div class="btn dropdown-toggle naviDrop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% if user.is_authenticated %}
                            User : {{ user.get_username }}
                            {% if user.icon.url != "" %}
                                <img src="{{ user.icon.url }}" style="height: 20px; width: 20px; border-radius: 50%;">
                            {% else %}
                            <img src="/static/img/export.png" style="height: 20px; width: 20px; border-radius: 50%;">
                            {% endif %}
                        {% else %}
                            User
                        {% endif %}          
                </div>
                {% if user.is_authenticated %}
                    <div class="dropdown-menu dropdown-menu-right" >
                    <a class="dropdown-item" href="{% url 'mk:profile' user.pk %}">マイページ</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/logout/">ログアウト</a>
                    </div>
                {% endif %}
            </div>
        </nav>

        <div class="drawr">
            <div class="barmenu top">タスク管理</div>
            <div class="barmenu"><a href="/">トップページ</a></div>
            <div class="barmenu"><a href="/task/">タスク</a></div>
            <div class="barmenu"><a href="/bmi/">BMI計算</a></div>
        </div>

        {% block body %}{% endblock %}

    </body> 
</html>

mk/templates/login.html
{% extends "base.html" %}
{% block title %} Makkyo ログイン {% endblock %}
{% block mainT %} ログイン {% endblock %}
{% block mainL %}User : {{ user.get_username }}{% endblock %}
{% block auth %}
{% endblock %}
{% block body %}
<div style='padding-top: 50px;'>
    <form action="" method="POST">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        {{ field }}
                        {{ field.errors }}
                        <hr>
                    {% endfor %}
                    <button type="submit" class="btn btn-lg btn-primary btn-block" >ログイン</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                    {% csrf_token %}
                </div>
            </div>
            <div class="authElement">
                <a class="btn btn-outline-secondary" href="/registration/">アカウント登録</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mk/templates/logout.html
{% extends "base.html" %}
{% block title %} Makkyo ログアウト {% endblock %}
{% block mainT %} ログアウト {% endblock %}
{% block mainL %}UserID : {{ user.get_username }}{% endblock %}
{% block auth %}{% endblock %}
{% block body %}
    <div style="text-align: center; padding-top: 50px;">
    <h2 >また来てね!</h2>
    <a class="nav-link" href="../login/">ログイン</a>
    </div>
{% endblock %}

mk/templates/password_change.html
{% extends "base.html" %}
{% block title %} Makkyo {% endblock %}
{% block mainT %} パスワード変更 {% endblock %}
{% block body %}
<div style="margin:20px">
    <form action="" method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="form-group">
            <label class="col-6" for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            <span style="color:red">{{ field.errors }}<span>
        </div>
        {% endfor %}
        {% csrf_token %}
        <div class="form-group row">
            <div class="authElement">
                <button type="submit" class="btn btn-success">変更</button>
            </div>
            <div class="authElement">
                <a href="{% url 'mk:profile' user.pk %}" class="btn btn-primary">戻る</a>
            </div>
        </div>
    </form>

</div>
{% endblock %}

mk/templates/password_change_complete.html
{% extends "base.html" %}
{% block title %} Makkyo {% endblock %}
{% block mainT %} パスワード変更 {% endblock %}
{% block body %}
<div style="text-align: center; padding-top: 50px;">
    <h2 >パスワードを変更しました</h2>
    <div class="authElement">
        <a href="{% url 'mk:profile' user.pk %}" class="btn btn-primary">マイページ</a>
    </div>
</div>
{% endblock %}

mk/templates/profile.html
{% extends "base.html" %}
{% block title %} Makkyo {% endblock %}
{% block mainT %} アカウント情報 {% endblock %}
{% block body %}
<div style="margin:20px">
    <div class="icon">
        {% if user.icon.url != "" %}
            <img src="{{ user.icon.url }}" style="height: 100px; width: 100px; border-radius: 50%;">
        {% else %}
            <img src="/static/img/export.png" style="height: 50px; width: 50px; border-radius: 50%;">
        {% endif %}
    </div>
    <table class="table">
        <tbody>
            <tr>
                <th>ユーザー名</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>性別</th>
                <td>{{ user.gender }}</td>
            </tr>
            <tr>
                <th>生年月日</th>
                <td>{{ user.birthdate }}</td>
            </tr>
            <tr>
                <th>メールアドレス</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>姓</th>
                <td>{{ user.last_name }}</td>
            </tr>
            <tr>
                <th>名</th>
                <td>{{ user.first_name }}</td>
            </tr>
        </tbody>
    </table> 
    <a href="{% url 'mk:profile_update' user.pk %}" class="btn btn-primary ">変更</a>
    <a href="{% url 'mk:password' user.pk %}" class="btn btn-primary ">パスワード変更</a>
</div>
{% endblock %}

mk/templates/profile_update.html
{% extends "base.html" %}
{% block title %} Makkyo {% endblock %}
{% block mainT %} アカウント情報 更新 {% endblock %}
{% block body %}
<div style="margin:20px">
    <form action="" method="POST" enctype ="multipart/form-data">
        {{ form.non_field_errors }}
        <table class="table">
            <tbody>
                {% for field in form %}
                    <tr>
                        <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                        <td>{{ field }} <span style="color:red">{{ field.errors }}<span></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% csrf_token %}
        <button type="submit" class="btn btn-success" >更新</button>
    </form>
</div>
{% endblock %}

mk/templates/registration.html
{% extends "base.html" %}
{% block title %} Makkyo アカウント作成 {% endblock %}
{% block mainT %} アカウント作成 {% endblock %}
{% block mainL %}User : {{ user.get_username }}{% endblock %}
{% block auth %}
{% endblock %}
{% block body %}

<div style="padding:20px 200px 0px 200px;">
    <form action="" method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            <span style="color:red">{{ field.errors }}<span>
        </div>
        {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">登録</button>
    </form>
</div>
{% endblock %}

mk/templates/registration_complete.html
<div style="text-align: center; padding-top: 50px;">
    <h2 >登録が完了しました</h2>
    <a class="nav-link" href="/login/">ログイン</a>
</div>

mk/templates/top.html
{% extends "base.html" %}
{% block title %} Makkyo {% endblock %}
{% block mainT %} トップメニュー {% endblock %}
{% block mainL %}UserID : {{ user.get_username }}{% endblock %}
{% block auth %}<a class="nav-link" href="../logout/">ログアウト</a>{% endblock %}
{% block body %}
    <br>
    </br>
    <h2 style="text-align: center;"><b>時 &nbsp;報</b></h2> 
    <br>
    </br> 
    <h2 style="text-align: center;"><p id="Clock"></p></h2>
{% endblock %}

            
            